version: '3.1'
services:
  poc-quarkus:
    build: ./src/main/docker/Dockerfile.native
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus
    container_name: prometheus_started
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana_started
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus